### ISSUE TITLE
Champ << Login >> manquant, table utilisateur

### ISSUE THREAD

**Issue by JonathanCHHAY** [JonathanCHHAY/star_wars_auction#11]
Il faudrait rajouter un champ << login >> à la table utilisateur. Sinon on est obligé d'identifier un utilisateur avec son nom, ce qui n'est pas pratique.

**Comment by gprog39** [comment]
Je réfléchis à la question :)

**Comment by JonathanCHHAY** [comment]
Dac ! ^^
